# Generated by Django 3.2.19 on 2023-07-01 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_auto_20230701_1004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='company_register_tb1',
            new_name='company_register_tb',
        ),
    ]
