# Generated by Django 3.2.19 on 2023-07-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_rename_company_register_tb1_company_register_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_register_tb',
            name='cover',
            field=models.ImageField(upload_to='media/company_cover/'),
        ),
        migrations.AlterField(
            model_name='company_register_tb',
            name='logo',
            field=models.ImageField(upload_to='media/company_logo/'),
        ),
    ]
