# Generated by Django 3.2.19 on 2023-07-03 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_auto_20230703_0941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='company_register_tb1',
            new_name='company_register_tb',
        ),
    ]
