# Generated by Django 3.2.19 on 2023-07-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_rename_company_register_tb1_company_register_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_register_tb',
            name='cover',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='company_register_tb',
            name='logo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
