# Generated by Django 3.2.19 on 2023-07-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0014_auto_20230703_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_register_tb',
            name='cover',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='company_register_tb',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
