# Generated by Django 3.2.19 on 2023-07-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0015_auto_20230703_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_job_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=225)),
                ('cat', models.CharField(max_length=225)),
                ('type', models.CharField(max_length=225)),
                ('salary', models.CharField(max_length=225)),
                ('min', models.CharField(max_length=225)),
                ('max', models.CharField(max_length=225)),
                ('skills', models.CharField(max_length=225)),
                ('qualification', models.CharField(max_length=225)),
                ('exp', models.CharField(max_length=225)),
                ('require', models.CharField(max_length=225)),
                ('nos', models.CharField(max_length=225)),
                ('loca', models.CharField(max_length=225)),
            ],
        ),
    ]
