# Generated by Django 3.2.19 on 2023-07-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_auto_20230708_1101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post_job_tb1',
            new_name='post_job_tb',
        ),
    ]
