# Generated by Django 3.2.19 on 2023-07-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_rename_post_job_tb1_post_job_tb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='company_register_tb',
            new_name='company_register_tb1',
        ),
    ]
