# Generated by Django 3.2.19 on 2023-07-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0019_rename_company_register_tb_company_register_tb1'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant_register_tb1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=225)),
                ('uname', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=255)),
                ('profile', models.ImageField(upload_to='userprofile/')),
                ('cv', models.FileField(upload_to='cv/')),
                ('dob', models.DateField(max_length=225)),
                ('loction', models.CharField(max_length=225)),
                ('phone', models.IntegerField(max_length=225)),
                ('website', models.CharField(max_length=225)),
                ('companyname', models.CharField(max_length=225)),
                ('designation', models.CharField(max_length=225)),
                ('qualification', models.CharField(max_length=225)),
                ('language', models.CharField(max_length=225)),
                ('desc', models.CharField(max_length=225)),
                ('linkedin', models.CharField(max_length=225)),
                ('github', models.CharField(max_length=225)),
                ('dribbble', models.CharField(max_length=225)),
                ('pinterest', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='applicant_register_tb',
        ),
    ]
