# Generated by Django 3.2.19 on 2023-07-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0020_auto_20230717_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='applicant_register_tb1',
            new_name='applicant_register_tb',
        ),
    ]
