# Generated by Django 3.2.19 on 2023-07-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_rename_applicant_register_tb1_applicant_register_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_register_tb',
            name='dob',
            field=models.CharField(max_length=225),
        ),
    ]
