# Generated by Django 3.2.19 on 2023-07-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0022_alter_applicant_register_tb_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_register_tb',
            name='phone',
            field=models.CharField(max_length=225),
        ),
    ]
