# Generated by Django 3.2.19 on 2023-07-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0023_alter_applicant_register_tb_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply_job_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.company_register_tb1')),
                ('jid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.post_job_tb')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.applicant_register_tb')),
            ],
        ),
    ]
