# Generated by Django 3.2.19 on 2023-07-21 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0026_interview_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='interview_tb1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=225)),
                ('time', models.CharField(max_length=225)),
                ('require', models.CharField(max_length=225)),
                ('msg', models.CharField(max_length=225)),
                ('loca', models.CharField(max_length=225)),
                ('link', models.CharField(max_length=225)),
                ('aplyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.apply_job_tb')),
                ('cmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.company_register_tb1')),
                ('jid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.post_job_tb')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.applicant_register_tb')),
            ],
        ),
        migrations.DeleteModel(
            name='interview_tb',
        ),
    ]
