# Generated by Django 3.2.19 on 2023-07-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0027_auto_20230721_1615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='interview_tb1',
            new_name='interview_tb',
        ),
    ]
