# Generated by Django 3.2.19 on 2023-07-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0029_auto_20230725_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post_job_tb1',
            new_name='post_job_tb',
        ),
        migrations.RenameField(
            model_name='post_job_tb',
            old_name='lastdate',
            new_name='lastdata',
        ),
    ]
