# Generated by Django 3.2.19 on 2023-07-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0030_auto_20230725_1217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post_job_tb',
            new_name='post_job_tb1',
        ),
    ]
