# Generated by Django 3.2.19 on 2023-07-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0031_rename_post_job_tb_post_job_tb1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post_job_tb1',
            new_name='post_job_tb',
        ),
    ]
