# Generated by Django 3.2.20 on 2023-07-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0032_rename_post_job_tb1_post_job_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_job_tb',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
