# Generated by Django 3.2.20 on 2023-08-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0035_alter_post_job_tb_lastdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job_tb',
            name='date',
            field=models.DateField(default='2023-08-25'),
        ),
    ]
